#!/usr/bin/env python3
"""
Import ablation_test_report.json into SQLite.

Usage:
    python import_ablation_json_to_sqlite.py \
        --json ablation_test_report.json \
        --db ablation_test.db \
        --schema create_ablation_db.sql

The import is idempotent:
- (stage, experiment name) identifies an experiment.
- Re-importing updates its configuration and replaces its metrics.
"""

from __future__ import annotations

import argparse
import json
import math
import sqlite3
from pathlib import Path
from typing import Any, Iterable


KNOWN_FEATURES = (
    "attn_last",
    "attn_all",
    "conf",
    "margin",
    "entropy",
    "pos_delta",
    "mask_density",
    "x0_stability",
    "step_progress",
)

# When a metric is represented by a summary dictionary, use one of these keys
# as the scalar value stored in metric_value.
PRIMARY_VALUE_KEYS = (
    "mean",
    "avg",
    "average",
    "value",
    "score",
    "median",
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--json",
        default="ablation_test_report.json",
        help="Path to the JSON report.",
    )
    parser.add_argument(
        "--db",
        default="ablation_test.db",
        help="Path to the SQLite database.",
    )
    parser.add_argument(
        "--schema",
        default="create_ablation_db.sql",
        help="Path to the SQL schema file.",
    )
    parser.add_argument(
        "--stage",
        action="append",
        dest="stages",
        help=(
            "Import only this stage. Repeat for multiple stages. "
            "By default, all stages are imported."
        ),
    )
    return parser.parse_args()


def json_text(value: Any) -> str:
    return json.dumps(
        value,
        ensure_ascii=False,
        separators=(",", ":"),
        allow_nan=False,
    )


def finite_number(value: Any) -> float | None:
    """Return a finite float for numeric values; reject bool, NaN, and infinity."""
    if isinstance(value, bool):
        return None
    if isinstance(value, (int, float)):
        number = float(value)
        return number if math.isfinite(number) else None
    return None


def extract_primary_number(value: Any) -> float | None:
    """
    Convert a metric payload into one queryable scalar.

    Supported examples:
        0.77
        {"mean": 0.77, "std": 0.04}
        {"average": 0.77}
        [0.77, 0.76, 0.79]

    The complete payload is always preserved in metric_json.
    """
    direct = finite_number(value)
    if direct is not None:
        return direct

    if isinstance(value, dict):
        for key in PRIMARY_VALUE_KEYS:
            if key in value:
                result = extract_primary_number(value[key])
                if result is not None:
                    return result

        # Fallback for an unfamiliar summary format.
        for nested_value in value.values():
            result = extract_primary_number(nested_value)
            if result is not None:
                return result
        return None

    if isinstance(value, (list, tuple)):
        for item in value:
            result = extract_primary_number(item)
            if result is not None:
                return result

    return None


def iter_metric_rows(metrics: Any) -> Iterable[tuple[str, str, float | None, str]]:
    """
    Yield:
        (result_group, metric_name, metric_value, metric_json)

    The report generated by ablation_test_common.py normally has:
        metrics["all"]["recall@5"]
        metrics["all"]["pr_auc@5"]

    It may also contain pass/fail groups or metadata such as a checkpoint path.
    """
    if not isinstance(metrics, dict):
        return

    for group_name, group_payload in metrics.items():
        if isinstance(group_payload, dict):
            for metric_name, metric_payload in group_payload.items():
                yield (
                    str(group_name),
                    str(metric_name),
                    extract_primary_number(metric_payload),
                    json_text(metric_payload),
                )
        else:
            # Preserve scalar/string metadata under a dedicated result group.
            yield (
                "_meta",
                str(group_name),
                extract_primary_number(group_payload),
                json_text(group_payload),
            )


def apply_schema(connection: sqlite3.Connection, schema_path: Path) -> None:
    connection.executescript(schema_path.read_text(encoding="utf-8"))


def upsert_experiment(
    connection: sqlite3.Connection,
    stage: str,
    record: dict[str, Any],
) -> int:
    config = record.get("config") or {}
    features = list(config.get("features") or [])
    feature_set = set(features)
    router_kwargs = config.get("router_kwargs") or {}
    error = record.get("error")
    status = "error" if error else "ok"

    values = {
        "stage": stage,
        "name": str(record.get("name", "")),
        "status": status,
        "error_message": error,
        "normalization": config.get("normalization"),
        "loss": config.get("loss"),
        "loss_pos_weight": config.get("loss_pos_weight"),
        "router": config.get("router"),
        "dim_hidden": router_kwargs.get("dim_hidden"),
        "num_blocks_mlp": router_kwargs.get("num_blocks_mlp"),
        "h": config.get("h"),
        "size_block": config.get("size_block"),
        "device": config.get("device"),
        "num_layers": config.get("num_layers"),
        "num_epochs": config.get("num_epochs"),
        "learning_rate": config.get("lr"),
        "weight_decay": config.get("weight_decay"),
        "holdout": config.get("holdout"),
        "filter_result": config.get("filter_result"),
        "seed": config.get("seed"),
        "feature_count": len(features),
        "feature_attn_last": int("attn_last" in feature_set),
        "feature_attn_all": int("attn_all" in feature_set),
        "feature_conf": int("conf" in feature_set),
        "feature_margin": int("margin" in feature_set),
        "feature_entropy": int("entropy" in feature_set),
        "feature_pos_delta": int("pos_delta" in feature_set),
        "feature_mask_density": int("mask_density" in feature_set),
        "feature_x0_stability": int("x0_stability" in feature_set),
        "feature_step_progress": int("step_progress" in feature_set),
        "features_json": json_text(features),
        "config_json": json_text(config),
        "raw_record_json": json_text(record),
    }

    columns = list(values)
    placeholders = ", ".join(f":{column}" for column in columns)
    updates = ", ".join(
        f"{column} = excluded.{column}"
        for column in columns
        if column not in {"stage", "name"}
    )

    connection.execute(
        f"""
        INSERT INTO experiments ({", ".join(columns)})
        VALUES ({placeholders})
        ON CONFLICT(stage, name) DO UPDATE SET
            {updates},
            imported_at = CURRENT_TIMESTAMP
        """,
        values,
    )

    row = connection.execute(
        "SELECT id FROM experiments WHERE stage = ? AND name = ?",
        (stage, values["name"]),
    ).fetchone()
    if row is None:
        raise RuntimeError(f"Failed to retrieve experiment: {stage}/{values['name']}")
    return int(row[0])


def replace_metrics(
    connection: sqlite3.Connection,
    experiment_id: int,
    metrics: Any,
) -> int:
    connection.execute(
        "DELETE FROM experiment_metrics WHERE experiment_id = ?",
        (experiment_id,),
    )

    count = 0
    for result_group, metric_name, metric_value, metric_json in iter_metric_rows(metrics):
        connection.execute(
            """
            INSERT INTO experiment_metrics (
                experiment_id,
                result_group,
                metric_name,
                metric_value,
                metric_json
            )
            VALUES (?, ?, ?, ?, ?)
            """,
            (
                experiment_id,
                result_group,
                metric_name,
                metric_value,
                metric_json,
            ),
        )
        count += 1
    return count


def import_report(
    connection: sqlite3.Connection,
    report: dict[str, Any],
    selected_stages: set[str] | None,
) -> tuple[int, int]:
    experiment_count = 0
    metric_count = 0

    for stage, records in report.items():
        if selected_stages is not None and stage not in selected_stages:
            continue
        if not isinstance(records, list):
            print(f"Skipping {stage!r}: expected a list of records")
            continue

        for record in records:
            if not isinstance(record, dict):
                print(f"Skipping a non-object record in {stage!r}")
                continue

            experiment_id = upsert_experiment(connection, stage, record)
            metric_count += replace_metrics(
                connection,
                experiment_id,
                record.get("metrics"),
            )
            experiment_count += 1

    return experiment_count, metric_count


def main() -> None:
    args = parse_args()
    json_path = Path(args.json)
    db_path = Path(args.db)
    schema_path = Path(args.schema)

    if not json_path.exists():
        raise FileNotFoundError(f"JSON report not found: {json_path}")
    if not schema_path.exists():
        raise FileNotFoundError(f"SQL schema not found: {schema_path}")

    with json_path.open("r", encoding="utf-8") as file:
        report = json.load(file)
    if not isinstance(report, dict):
        raise ValueError("The JSON report root must be an object keyed by stage")

    db_path.parent.mkdir(parents=True, exist_ok=True)
    selected_stages = set(args.stages) if args.stages else None

    connection = sqlite3.connect(db_path)
    try:
        connection.execute("PRAGMA foreign_keys = ON")
        apply_schema(connection, schema_path)

        with connection:
            experiments, metrics = import_report(
                connection,
                report,
                selected_stages,
            )

        print(f"Imported {experiments} experiments and {metrics} metric rows")
        print(f"Database: {db_path.resolve()}")

        stage_b_count = connection.execute(
            "SELECT COUNT(*) FROM experiments WHERE stage = 'stage_b'"
        ).fetchone()[0]
        print(f"Stage B rows: {stage_b_count}")

        print("\nTop Stage B configurations by recall@5:")
        rows = connection.execute(
            """
            SELECT
                name,
                normalization,
                loss,
                recall_at_5,
                pr_auc_at_5
            FROM stage_b_summary
            WHERE status = 'ok'
              AND recall_at_5 IS NOT NULL
            ORDER BY
                recall_at_5 DESC,
                pr_auc_at_5 DESC
            LIMIT 10
            """
        ).fetchall()

        for row in rows:
            print(row)

    finally:
        connection.close()


if __name__ == "__main__":
    main()
